# Generated by Django 5.1.4 on 2025-02-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashly_app', '0002_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
