# Generated by Django 5.1.4 on 2025-02-08 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashly_app', '0003_alter_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
    ]
