# Generated by Django 5.1.4 on 2025-02-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashly_app', '0004_remove_category_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
